[package]
name = "http_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
deluxe = "0.5.0"
lazy_static = "1.5.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
regex = "1.11.1"
syn = "2.0.104"
