[package]
name = "rust_http_server"
version = "0.1.0"
edition = "2024"

[dependencies]
http_macro = { path = "http_macro" }
http_types = { path = "http_types" }
async_lib = {path = "async_lib"}
lazy_static = "1.4.0"
regex = "1.10.5"
