[package]
name = "http"
version = "0.1.0"
edition = "2024"

[dependencies]
http_macro = { path = "http_macro" }
http_types = { path = "http_types" }
async_lib  = { path = "async_lib" }
html_types = { path = "html_types" }
html_macros ={ path = "html_macros" }
lazy_static = "1.4.0"
regex = "1.10.5"
