[package]
name = "http_types"
version = "0.1.0"
edition = "2024"

[dependencies]
http_macro = { path = "../http_macro" }
chrono = "0.4.41"
lazy_static = "1.5.0"
regex = "1.11.1"
urlencoding = "2.1.3"
httpdate = "1.0.3"
